<!-- ***********INTRODUCTION SECTION*************************************** -->

#Introduction

##Basic Information and Life History

*Population Structure and Complex Assessment Considerations*

There have been a number of analyses conducted on the genetic differentiation between 
gopher rockfish and black-and-yellow rockfish.  The studies have yielded a range of 
results, but have generally concluded that there is unusually low genetic 
differentiation between the two species. The most frequently used measure of
genetic analyses to evaluate evidence for population differentiation is the 
fixation index ($F_{ST}$), defined as the proportion of the total genetic 
variation in one sub-population (subscript S) relative to the total genetic 
variation (subscript T) [@Waples2008; @Hauser2008].   Values of $F_{ST}$ 
range from 0 to 1 where a zero value implies the populations are panmictic 
and a value closer to one implies the two populations are genetically 
independent. Values of $F_{ST}$ thought to be consistent with biologically 
meaningful genetic differentiation and demographic isolation between populations 
range from 0.05 to 0.1 [@Waples2006].   It is also important to note that $F_{ST}$ 
values are dependent on the study’s sample size and it may not necessarily be 
appropriate to compare them across studies. 

Morphologically, gopher and black-and-yellow rockfishes are almost indistinct, 
except for their color variation [@Hubbs1933]. Early efforts to evaluate whether 
the two species were genetically distinct began with an allozyme analysis by 
Seeb et al. [-@Seeb1986], which did not detect genetic differentiation between 
gopher and black-and-yellow rockfish.  However, as allozymes are proteins that 
are often conserved, this early work was not necessarily representative of 
genome-wide relationships between the two groups.
In a subsequent study of restriction site polymorphisms, 
Hunter et al. [-@Hunter1994] found slight but significant differences between 
species based on restriction fragment length polymorphisms (RFLP’s).  Following 
that study, an analysis of the mitochondrial control region by Alesandrini and 
Bernardi [-@Alesandrini1999] did not detect differences between the two species, 
although mtDNA also has limitations regarding how results can be extrapolated
across the nuclear genome. Analysis of seven microsatellite loci by Narum et al. [-@Narum2004] 
found an $F_{ST}$ of 0.049 across the overlapping range of the two species, which 
provided some evidence of divergence, although such divergence is relatively low 
compared to other species within *Sebastes*.  Those authors characterized their 
results as suggesting that the two are “reproductively isolated incipient species.” 
Buonaccorsi et al. [-@Buonaccorsi2011] found an even lower $F_{ST}$ of 0.01 using 
25 microsatellite loci, and concluded that gopher and black-and-yellow rockfish “have not 
completed the speciation process.”  All of these studies are indicative of low 
levels of genetic divergence and a high probability of ongoing gene flow between 
the two nominal species.  

Most recently, an analysis of rockfish species assignment using microhaplotypes by 
Baetscher [-@Baetscher2019] observed mistaken genetic assignment of a small number 
of individuals between gopher and black-and-yellow rockfishes, while no other 
species among the 54 rockfishes analyzed resulted in mis-assignments. In addition, comparisons 
of $F_{ST}$  values within the study indicated that the level of genetic differentiation 
observed between gopher and black-and-yellow rockfishes is lower than that observed among 
all other pairwise comparisons of the 54 species in the *Sebastes* genus that were included 
in their analysis. Baetscher [-@Baetscher2019] characterized the results as suggestive of 
the two species representing “sister species with evidence of ongoing gene flow,” noting 
that a more rigorous evaluation of the level of genetic distinction between these two species 
would benefit from whole-genome sequencing of representatives from each species group.

In addition to the differences in coloration, the depth distribution and range 
differ between the two species. The range of both species extends from Cape 
Blanco Oregon to Baja California. Both species are uncommon north of Fort Bragg, 
California and black-and-yellow rockfish is uncommon south of Point Conception, 
California. However, gopher rockfish can be found as far south as Punta San Roque on the 
Baja peninsula.Gopher rockfish are found in rocky reef habitat from the intertidal 
to depths of 264 ft (80 m) 
with a predominant depth distribution of 30 to 120 ft (9-37 m), while the 
black-and-yellow rockfish occupies depths from the intertidal to 120 ft (40 m) 
and is predominantly observed in depths shallower than 60 ft (18 m) 
[@Eschmeyer1983; @Love2002]. 

Both species are solitary, sedentary, and territorial species with home 
ranges of 10-12 square meters [@Love2002]. 
A large percentage (67-71%) of black-and-yellow rockfish returned to the site 
of capture within two weeks after translocated within 50 m [@Hallacher1984].
Lea et al. [-@Lea1999] found that gopher rockfish exhibit minor patterns of 
movement (<12.8 km) with all fish being recaptured on the same reef 
system where they were tagged. Matthews [-@Matthews1985] found that 11.8% 
of tagged and recaptured gopher rockfish, and 25% of black-and-yellow rockfish, 
moved from four low-relief natural reefs to a new high-relief artificial reef in 
Monterey Bay.  The maximum distance between the natural and artificial reefs 
traveled by gopher or black-and-yellow rockfish was 1.6 km. After only a year, 
the fish assemblage 
on the artificial reef closely resembled that of the nearby natural reefs. The 
paper did not address the spatial segregation of gopher and black-and-yellow rockfish 
on the new artificial reef.

Larson [-@Larson1980] conducted a study on the territoriality and segregation 
between gopher and black-and-yellow rockfishes.  When one species was removed, 
the other extended its depth range to areas where the other previously occupied, 
indicating inter-specific competition plays a role in controlling their depth 
distributions where both species are present. Of the two species, black-and-yellow 
rockfish are socially dominant and aggressive towards excluding gopher rockfish 
from shallower waters.

Both species are be feed at night, with similar diets composed primarily of 
crabs and shrimp,supplemented by fish and cephalopods [@Love2002; 
-@Hallacher1985; @Larson1972]. Loury et al. [-@Loury2015] found no significant 
differences in the diet of gopher rockfish inside and outside the 35 year old Point Lobos 
Marine Protected Area (MPA). She did find the diet of gopher rockfish at A&ntilde;o Nuevo 
(shallower and north of Point Lobos) was dominated by crabs and dominated by brittle 
stars at southern, deeper study locations. Zuercher [-@Zuercher2019] examined the 
diets of a suite of nearshore rockfish species including black-and-yellow and found 
that they relied on hard-bodied benthic invertebrates such as Brachyuran crabs, 
shrimps, other arthropods, and octopus. The diet of black-and-yellow rockfish 
remained the same across sampling years, 
but they occupied a lower trophic level during the upwelling season. 

## Early Life History
Gopher and black-and-yellow rockfish have similar juvenile development. 
Both rockfish species are viviparous and release one brood per 
season between January and July [@Echeverria1987].  Larvae are approximately 4 mm in length 
at birth and have a 1-2 month pelagic stage before recruiting to the kelp forest canopy, 
i.e., surface fronds of \emph{Macrosystis pyrifera} and \emph{Cysteoseira osmundacea} 
at around 15-21 mm [@Anderson1983; @Wilson2008]. The larvae are transparent until they 
reach juvenile stage at 22-23 mm. Differences in coloration between the two species begin 
to occur at 25-30 mm and can be used to identify one species from the other. Gopher 
rockfish become more orange and brown, while black-and-yellow rockfish become more 
black and yellow. Benthic juveniles associate with \emph{Macrosystis} holdfasts and 
sporophylls [@Anderson1983]. 

The juveniles undergo ontogenetic migration down the stalks to deeper depths, 
finally settling on rocky reef habitat in their respective adult depth distribution. 
Juvenile bocaccio and other fish predate on young of year and other reef dwelling 
species including cabezon predate on post-settlement juveniles. Individuals avoid 
rough surge conditions and predators by hiding in the rocky bottom during the 
daylight hours, then returning to more open water at dusk [@Love2002]. 


##Map
A map showing the scope of the assessment and depicting boundaries at 
Cape Mendocino to the north and the U.S./ Mexico border at the south 
(Figure \ref{fig:assess_region_map1}). The recreational fishing fleet 
was split into two fleets at Point Conception. 


##Ecosystem Considerations
In this assessment, ecosystem considerations were not explicitly included in the 
analysis. This is primarily due to a lack of relevant data and results of 
analyses (conducted elsewhere) that could contribute ecosystem-related 
quantitative information for the assessment.


##Fishery Information

The hook-and-line fishery off California developed in the late 19th century 
[@Love2002]. The rockfish trawl fishery was established in the early 1940s, when 
the United States became involved in World War II and wartime shortage of red 
meat created an increased demand for other sources of protein [@Alverson1964; 
@Harry1961]. 

Gopher and black-and-yellow (referred to from hereon as GBYR when discussing the 
complex) rockfish have been a minor component of the commercial and recreational 
rockfish fishery since at least the late 1960s (CFIS and RecFIN). The commercial 
catch histories of the two species cannot easily be separated 
(Figure \ref{fig:Catches_livedeadNS_gby}).  From 1916-1936 
only black-and-yellow rockfish were reported in the landings, and an average 
of 0.04 mt of black-and-yellow rockfish are reported from 1937-1983. 
Black-and-yellow rockfish reappear in the landings in 1984 with 7.2 mt landed 
commercially. From 1985-1988 the trend switches and only black-and-yellow 
rockfish appear in the commercial landings, with gopher rockfish averaging 0.1 mt
landed, and 0 mt reported in 1987. From 1988 and on, the landings are dominated 
by gopher rockfish, and both species are represented in the commercial landings. 

The landings from south of Point Conception are minor throughout the time period, 
with peaks in the 1950s and 60s for gopher rockfish.  Black-and-yellow rockfish 
are rare south of Point Conception and expected that these catches are minimal. 

The live fish fishery began in the early 1990s, with the first reported commercial landings 
of live gopher rockfish in 1993, and black-and-yellow rockfish a year later. By 1995 
over half (57%; 39 mt) of the commercial landings were from the live fish fishery. 
This increased quickly over the next few years and has been on average 84% of the landed 
gopher and black-and-yellow rockfish (also referred to GBYR to reference the complex in this
assessment) since 2000.  The majority of the landings are from gopher rockfish north of Point 
Conception.  Landings of live GBYR south of Point Conception were higher in the late 
1990s, (max. 3.2 mt in 1999), and have been averaging 0.4 mt since 2003. 

The ex-vessel value of GBYR increased from less than $40,000 in 1984 and peaked 
at $680,452 in 1996 (Figure \ref{fig:GBY_revenue}).  The ex-vessel revenue has 
been fairly stable at around $500,000 a year since 2007.  Prior to the live 
fish fishery in 1994, the average price per pound for either species was around 
$2 a pound.  The live fish fishery increased the value of both species to an 
average of \$6-\$8 a pound.  The maximum reported value of either a gopher 
or black-and-yellow rockfish was $20 a pound in 2003.

The recreational GBYR fishery for California is most prominent north of Point 
Conception throughout the entire catch history (Figure \ref{fig:Exec_catch1}).
The recreational landings increased from 1928 to 1980.  The sharp increase 
in the 1980s could be an artifact of the MRFSS sampling program that began 
in 1980; however, the more recent recreational landings also exhibit a cyclical 
trend of years with high catches followed by period of decreased recreational 
landings. The CRFS era recreational total mortality represents the most accurate 
description of the recreational fleet's catches in terms of area, mode and species 
(Figure \ref{fig:CFRS_catches}).  

Recreational GBYR catches are dominated by gopher 
rockfish north of Point Conception in the private/rental (PR) and party/charter 
(PC or CPFV) modes.  South of Point Conception gopher rockfish are predominately 
caught by the CPFV fleet, with all other modes being insignificant. The total 
recreational mortality of black-and-yellow rockfish south of Point Conception 
since 2005 is 3 mt, compared to 106 mt north of Point Conception. The total 
mortality since 2005 for gopher rockfish is 86 mt south of Point Conception 
and 669 mt north of Point Conception.


##Summary of Management History

Prior to the adoption of the Pacific Coast Groundfish Fishery Management Plan (FMP) 
in 1982, GBYR were managed through a regulatory 
process that included the California Department of Fish and Wildlife (CDFW) along 
with either the California State Legislature or the Fish and Game Commission (FGC) 
depending on the sector (recreation or commercial) and fishery. With implementation 
of the Pacific Coast Groundfish FMP, GBYR came under the management 
authority of the Pacific Fishery Management Council (PFMC), and were managed as part 
of the *Sebastes* complex. Because neither species had undergone rigorous stock assessment 
and did not compose a large fraction of the landings they were classified and 
managed as part of "Remaining Rockfish" under the larger 
heading of "Other Rockfish" (PFMC [-@PFMC2004; -@PFMC2002]).

Since the early 1980s a number of federal regulatory measures have been used to 
manage the commercial rockfish fishery including cumulative trip limits (generally 
for two- month periods) and seasons. Starting in 1994 the commercial groundfish 
fishery sector was divided into two components: limited entry and open access 
with specific regulations designed for each component. Other regulatory actions 
for the general rockfish categories have included area closures, gear restrictions, 
and cumulative bimonthly trip limits set for the four different commercial sectors - 
limited entry fixed gear, limited entry trawl, open access trawl, and open access non-trawl.
Harvest guidelines are also used to regulate the annual harvest for both the recreational and 
commercial sectors. 

In 2000, changes in the PFMC’s rockfish management structure resulted in the discontinued 
use of the \emph{Sebastes} complex, and was replaced with three species 
groups: nearshore, shelf, and slope rockfishes (January 4, 2000; 65 FR 221), of which GBYR are 
included in the nearshore group. Within the nearshore group, they are included in the 
“shallow nearshore rockfish” component. 

During the late 1990s and early 2000s, major changes also occurred in the way 
that California managed its nearshore fishery. The Marine Life Management Act 
(MLMA), which was passed in 1998 by the California Legislature and enacted in 
1999, required that the FGC adopt an FMP for nearshore finfish [@Vandenberg2014]. 
It also gave authority to the FGC to regulate commercial and recreational nearshore fisheries 
through FMPs and provided broad authority to adopt regulations for the nearshore 
fishery during the time prior to adoption of the nearshore finfish FMP. Within this 
legislation, the Legislature also included commercial size limits for ten nearshore
species including GBYR (10-inch minimum size) and a requirement 
that commercial fishermen landing these ten nearshore species possess a nearshore permit.

Following adoption of the Nearshore FMP and accompanying regulations by the FGC in 
fall of 2002, the FGC adopted regulations in November 2002 which established a set 
of marine reserves around the Channel Islands in southern California (which became 
effective April 2003).  The FGC also adopted a nearshore restricted access program in December 
2002 (which included the establishment of a Deeper Nearshore Permit) to be effective 
starting in the 2003 fishing year.

Also, since the enactment of the MLMA, the Council and State in a coordinated 
effort developed and adopted various management specifications to keep harvest 
within the harvest targets, including seasonal and area closures (e.g. the CCAs; 
a closure of Cordell Banks to specific fishing), depth restrictions, minimum 
size limits, and bag limits to regulate the recreational fishery and license 
and permit regulations, finfish trap permits, gear restrictions, seasonal 
and area closures (e.g. the RCAs and CCAs; a closure of Cordell Banks to 
specific fishing), depth restrictions, trip limits, and minimum size 
limits to regulate the commercial fishery.

The state of California has adopted regulatory measures to manage the fishery 
based on the harvest guidelines set forth by the PFMC.  The commercial open access 
and limited entry fixed gear sectors have undergone 
three different spatial management changes in since 2000.  Since 2005, both 
have managed the area south of $40^\circ 10^\prime$ N. latitude as one area. 
The open access commercial fishery is managed based on bimonthly 
allowable catches, that have ranged from 200 pounds to 1800 pounds per two months since 2000.
From 2005 to 2018, the catch limits have doubled and are now set at 1200 pounds per two 
months (for all months) with March and April remaining closed. The limited entry fixed year 
sector has followed the same pattern as the open access sector with bi-monthly limits 
and a doubling of the catch since 2005. The limited entry trawl fleet is managed on 
monthly limits on an annual basis. Since 2011, the limit has been 300 pounds per month for 
non-IFQ species.  A history of California's commercial regulations from 2000-2018 can be 
found in [Appendix A](#appendix-a.-californias-commercial-fishery-regulations). A 10-inch 
total length minimum size limit was implemented in 1999 for both species in the commercial fleet.

Significant regulatory changed in California's recreational sector began with a change 
from unlimited number of hooks and lines allowed in 1999 and prior to no more than 
three hooks and one line per angler in 2000.  Since 2001, the limit has been no more than 
two hooks and one line per angler.  There is no size limit in the recreational fishery 
for gopher or black-and-yellow rockfish.  GBYR are part of the nearshore complex which has 
had a sub-bag limit within the rockfish bag limit since 1999.  The nearshore sub-bag limit 
has been 10 fish since 2005.  

California also began spatial management, closures, and depth restrictions for the recreational 
fleet in 2000.  In general, the recreational season north of Point Conception extends from April to 
December, and south of Point Conception from March to December.  In the area that GBYR are most 
commonly landed, from Monterey to Morro Bay, the depth restrictions have been between 30 and 40 
fathoms until 2017.  In 2017 the depth restrictions were eased by 10 fathoms, opening up fishing 
depths along the central California coast that had not been open consistently since 2002.  In 
both 2017 and 2018, the deepest 10 fathoms was closed prior to the season in December due to high 
by-catch rates of yelloweye rockfish, one of two rockfish species that are still overfished. A 
full history of the recreational regulations relating to the spatial management of the fleet can 
be found in [Appendix B](#appendix-b.-californias-recreational-fishery-regulations).


##Management Performance
The contribution of GBYR to the minor nearshore rockfish OFLs is currently derived from 
two sources: 1) forecasts from Key et al. [-@Key2005], from Cape Mendocino to 
Point Conception, and 2) a Depletion Corrected Average Catch (DCAC [@MacCall2009]) for the 
area south of Point Conception. The total mortality of the minor nearshore rockfish has been 
below the ACL in all years (2011-2016). Total mortality estimates from the NWFSC are not yet available for 2017-2018. GBYR total mortality was on average 20% of the 
total minor nearshore rockfish total mortality from 2011-2016. A summary of these values 
as well as other base case summary results can be found in Table \ref{tab:mnmgt_perform}.


##Fisheries Off Mexico or Canada
The range of GBYR does not extend north to the Canadian border, and they are rarely 
encountered in Oregon and Washington.  The southern end of the gopher rockfish's range 
extends to Punta San Roque (southern Baja California) while the southern end of the 
black-and-yellow rockfish's range extends to Isla Natividad (central Baja California) 
[@Love2002]. However, black-and-yellow rockfish are rare south of Point Conception, California. 
This was no available information on the fishery for GBYR at the time 
of this assessment, nor additional details on the abundance or distribution patterns 
in Mexican waters.

