<!-- ====================================================================== -->
<!-- ****************************            ****************************** --> 
<!-- ****************************BEGIN TABLES****************************** --> 
<!-- ****************************             ***************************** --> 
<!-- ======================================================================--> 

\FloatBarrier

<!-- ********************************************************************** --> 
<!-- *********************Commercial landings TABLES*********************** --> 
<!-- ********************************************************************** --> 

```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
     Comm_removal = read.csv("./txt_files/Catch_stream_w_alts.csv")
      Comm_removal = Comm_removal %>% 
                     select(Year, Commercial, WCGOPalt1, CommSource) %>%
                     add_column(Total = 1, .before = 'CommSource') %>%
                     mutate(Total = Commercial + WCGOPalt1)
                              
     colnames(Comm_removal) = c('Year',
                                'Landings',
                                'Discards',
                                'Total Commercial Removals',
                                'Source')
```


```{r, results='asis'}
   Comm_removal.table = xtable(Comm_removal, 
                    caption = c("Commercial landings and discards (mt) from the commercial 
                                fisheries. Data sources are the California Catch 
                                Reconstruction, CALCOM, PacFIN, and WCGOP GEMM report."))

   align(Comm_removal.table) =c('l','c', 
                            '>{\\centering}p{1in}',
                            '>{\\centering}p{.6in}',
                            '>{\\centering}p{1in}',
                            'l')  
     print(Comm_removal.table,include.rownames=FALSE,      
           caption.placement="top",align=TRUE,tabular.environment="longtable",
            floating=FALSE,  #sanitize.text.function = function(x){x},
           add.to.row = list(pos = list(0),command = 
                        paste("\\hline  \\endfirsthead",  # First caption
                                "\\caption[]{Commercial landings and discards (mt) from the commercial 
                                fisheries. Data sources are the California Catch 
                                Reconstruction, CALCOM, PacFIN, and WCGOP GEMM report.} \\label{tab:CommCatches} \\\\ \\hline", # Addit. captions
                                paste(colnames(Comm_removal)[1], paste("&", colnames(Comm_removal)[2:5], collapse=" ")), # Column names
                                "\\\\ \\hline ",
                                "\\endhead", 
                                "\\hline \\multicolumn{4}{l}{\\textit{Continues next page}} \\ 
                                 \\endfoot
                                 \\endlastfoot",collapse=" ")))
```

\FloatBarrier

<!-- ********************************************************************** --> 
<!-- *****Fishery Length comp tables TABLES******* -->
<!-- ********************************************************************** --> 

```{r, results = 'asis'}
#Read in lengths table, make one for n fish lengthed and one for trips
#Fishery dependent data
lengths_sample = read.csv('C:/GopherBlackYellow2019/txt_files/LengthSampleSize2.csv')
lengths_sample = lengths_sample[,1:11]
#Make the multiheader table
colnames(lengths_sample) = c('Year','Trips','Lengths','Trips','Lengths','Trips','Lengths',
                                 'Trips','Lengths','Trips','Lengths')

a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  lengths_sample,
  # the labels of the groups that we want to insert
  grp_names = c("", "CALCOM", "WCGOP","Rec North","Rec South",
                     "Deb VW"),
  # the number of columns each group spans
  span = c(1, 2, 2, 2, 2, 2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)

caption = "Length composition sample sizes for fishery dependent data. Continuous years begin in 1975. 
           Recreational north samples include Karpov et al., MRFSS, and CRFS data. 
           Recreational south samples include Karpov et al., Collins and Crooke unpub.,
           Ally et al. 1991, MRFSS, and CRFS data."

lengths.table = xtable(lengths_sample,
                    caption = caption,
                    label = 'tab:length_samples_fishery')

align(lengths.table) = c('l', 'l',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}')

print(lengths.table, add.to.row = a_header, 
      caption.placement = "top", 
      include.rownames = F, hline.after = F, scalebox = .76)
```





\FloatBarrier
\newpage
<!-- ********************************************************************** --> 
<!-- ***********Recreational Landings and discards TABLE******************* --> 
<!-- ********************************************************************** --> 

```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
      Rec_removal = read.csv("./txt_files/Catch_stream_w_alts.csv")
       Rec_removal =  Rec_removal %>% 
                     select(Year, RecNorthalt1, RecSouthalt1, RecSource) %>%
                     filter(Year>1927) %>%
                     add_column(Total = 1, .before = 'RecSource') %>%
                     mutate(Total = RecNorthalt1 + RecSouthalt1)
                              
     colnames(Rec_removal) = c('Year',
                                'North of Pt. Conception',
                                'South of Pt. Conception',
                                'Total Recreational Removals',
                                'Source')
```


```{r, results='asis'}
   Rec_removal.table = xtable(Rec_removal, 
                    caption = c("Recreational removals (mt) of GBYR. Data sources are the California Catch 
                                Reconstruction (modified for south of Pt. Conception), MRFSS (modified for 1981-1982), and CRFS."))

   align(Rec_removal.table) =c('l','c', 
                            '>{\\centering}p{1.2in}',
                            '>{\\centering}p{1.2in}',
                            '>{\\centering}p{1in}',
                            'l')  
     print(Rec_removal.table,include.rownames=FALSE,      
           caption.placement="top",align=TRUE,tabular.environment="longtable",
            floating=FALSE,  #sanitize.text.function = function(x){x},
           add.to.row = list(pos = list(0),command = 
                        paste("\\hline  \\endfirsthead",  # First caption
                                "\\caption[]{Recreational removals (mt) of GBYR. Data sources are the California Catch 
                                Reconstruction (modified for south of Pt. Conception), 
                              MRFSS (modified for 1981-1982), and CRFS.} \\label{tab:Rec_removal} \\\\ \\hline", # Addit. captions
                                paste(colnames(Rec_removal)[1], paste("&", colnames(Rec_removal)[2:5], collapse=" ")), # Column names
                                "\\\\ \\hline ",
                                "\\endhead", 
                                "\\hline \\multicolumn{4}{l}{\\textit{Continues next page}} \\ 
                                 \\endfoot
                                 \\endlastfoot",collapse=" ")))
```



\newpage
\FloatBarrier


<!-- ********************************************************************** --> 
<!-- *****Survey Length comp tables TABLES******* -->
<!-- ********************************************************************** --> 

```{r, results = 'asis'}
#Read in lengths table, make one for n fish lengthed and one for trips
#Fishery independent data
lengths_sample1 = read.csv('C:/GopherBlackYellow2019/txt_files/LengthSampleSize2.csv')
lengths_sample1 = lengths_sample1 %>%
                  select(Year, CCFRPT:PISCOF) %>%
                  filter(Year>2000)
#Make the multiheader table
colnames(lengths_sample1) = c('Year','Trips','Lengths','Trips','Lengths')

a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  lengths_sample1,
  # the labels of the groups that we want to insert
  grp_names = c("","CCFRP","PISCO"),
  # the number of columns each group spans
  span = c(1, 2, 2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)

caption = "Length composition sample sizes for survey data."

lengths.table = xtable(lengths_sample1,
                    caption = caption,
                    label = 'tab:length_samples_survey')

align(lengths.table) = c('l', 'l',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}')

print(lengths.table, add.to.row = a_header, 
      caption.placement = "top", 
      include.rownames = F, hline.after = F)
```



\FloatBarrier
<!-- ********************************************************************** -->
<!-- *****Index TABLES with all indices - summary and index values******* -->
<!-- ********************************************************************** -->

<!--Index summary tables-->
```{r, results="asis"}
#read in index summary data
Index_summary = read.csv('./txt_files/Index_summary.csv')


Index_summary.table = xtable(Index_summary,
                            caption = c("Summary of indices used in this                                                   assessment."),
                            label='tab:Index_summary')
      

align(Index_summary.table) = c('l', 'r',
                               '>{\\centering}p{1in}',
                               '>{\\centering}p{2in}',
                               '>{\\centering}p{1in}',
                               '>{\\centering}p{1in}',
                               '>{\\centering}p{1in}',
                               '>{\\centering}p{1.5in}')

print(Index_summary.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              floating.environment = 'sidewaystable', 
              sanitize.text.function = function(x){x}) 
     
```



<!--Table with all index values-->
```{r, results = 'asis'}
#Read in indices table, contains index data for all indices
Indices = read.csv('./txt_files/Indices.csv')

#Make the multiheader table
colnames(Indices) = c('Year',"Obs","se_log","Obs","se_log"
                             ,"Obs","se_log","Obs","se_log"
                             ,"Obs","se_log","Obs","se_log"
                             ,"Obs","se_log")

a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  Indices,
  # the labels of the groups that we want to insert
  grp_names = c("", "Deb WV", "MRFSS N","MRFSS S","Onboard N",
                     "Onboard S","CCFRP","PISCO"),
  # the number of columns each group spans
  span = c(1, 2, 2, 2, 2, 2, 2, 2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)

caption = "Index inpus."

Indices.table = xtable(Indices,
                    caption = caption,
                    label = 'tab:Indices')


print(Indices.table, add.to.row = a_header, 
      caption.placement = "top", 
      include.rownames = F, hline.after = F, scalebox = .84)
```

\FloatBarrier
<!-- ********************************************************************** -->
<!-- *****Fleet 5 index TABLES******* -->
<!-- ********************************************************************** -->

```{r, results="asis"}
#read in index summary data for Fleet 5 - Deb's onboard
Fleet5_Filter = read.xlsx('./txt_files/Fleet5_DebWV_IndexData.xlsx', sheetName='Filter', header = T)
Fleet5_AIC = read.xlsx('./txt_files/Fleet5_DebWV_IndexData.xlsx', sheetName='AIC', header=T)

colnames(Fleet5_Filter) = c('Filter','Drifts','Positive Drifts')

Fleet5_Filter$Drifts = formatC(Fleet5_Filter$Drifts, digits = 0, format='f')
Fleet5_Filter$`Positive Drifts` = formatC(Fleet5_Filter$`Positive Drifts`, digits = 0, format='f')

Fleet5_Filter.table = xtable(Fleet5_Filter,
                       caption = c("Data filtering steps for Deb Wilson-Vandenberg's CPFV onboard observer 
                                        index of abundance"),
                       label = 'tab:Fleet5_Filter')


Fleet5_AIC.table = xtable(Fleet5_AIC,
                            caption = c("Model selection for Deb Wilson-Vandenberg's CPFV onboard observer 
                                        index of abundance. Bold values indicate the model selected."),
                            label='tab:Fleet5_AIC')
      


print(Fleet5_Filter.table, 
              include.rownames=FALSE, 
              caption.placement="top")


print(Fleet5_AIC.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})
     
```


\FloatBarrier

<!-- ********************************************************************** -->
<!-- *****Fleets 6 and 7 index TABLES******* -->
<!-- ********************************************************************** -->

```{r, results="asis"}
#read in index summary data for 2 onboard observer indices
Fleet6_7_Filter = read.xlsx('./txt_files/Fleet6and7_OnboardObserver_IndexData.xlsx', 
                            sheetName='BothFilter', header = T)

Fleet6_AIC = read.xlsx('./txt_files/Fleet6and7_OnboardObserver_IndexData.xlsx', sheetName='NorthAIC', header=T)
Fleet7_AIC = read.xlsx('./txt_files/Fleet6and7_OnboardObserver_IndexData.xlsx', sheetName='SouthAIC', header=T)


colnames(Fleet6_7_Filter) = c('Filter','Drifts','Positive Drifts')
Fleet6_7_Filter[10,] = c(NA,NA,NA)
Fleet6_7_Filter[14,] = c(NA,NA,NA)
Fleet6_7_Filter.table = xtable(Fleet6_7_Filter,
                       caption = c("Data filtering steps for the CRFS CPFV onboard observer 
                                        index of abundance for north and south of Pt. Conception."),
                       label = 'tab:Fleet6_7_Filter')
align(Fleet6_7_Filter.table) = c('l','l','c','c')
print(Fleet6_7_Filter.table, 
              include.rownames=FALSE, 
              caption.placement="top")


Fleet6_AIC.table = xtable(Fleet6_AIC,
                            caption = c("Model selection for the CRFS CPFV onboard observer 
                                        index of abundance for north of Pt. Conception. Bold 
                                        values indicate the model selected."),
                            label='tab:Fleet6_AIC')

print(Fleet6_AIC.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})


Fleet7_AIC.table = xtable(Fleet7_AIC,
                            caption = c("Model selection for the CRFS CPFV onboard observer 
                                        index of abundance for south of Pt. Conception. Bold 
                                        values indicate the model selected."),
                            label='tab:Fleet7_AIC')

print(Fleet7_AIC.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})
     
```



\FloatBarrier

<!-- ********************************************************************** -->
<!-- *****Fleets 8 index TABLES******* -->
<!-- ********************************************************************** -->

```{r, results="asis"}
#read in index summary data for PISCO
Fleet8_Filter = read.xlsx('./txt_files/Fleet8_PISCO_IndexData.xlsx', 
                            sheetName='Filter', header = T)

Fleet8_AIC = read.xlsx('./txt_files/Fleet8_PISCO_IndexData.xlsx', sheetName='AIC', header=T)

colnames(Fleet8_Filter) = c('Filter','Transects','Positive Transects')

Fleet8_Filter.table = xtable(Fleet8_Filter,
                       caption = c("Data filtering steps for the PISCO dive survey."),
                       label = 'tab:Fleet8_Filter',
                       digits = 0)


align(Fleet8_Filter.table) = c('l',
                               '>{\\raggedright}p{4in}',
                               'c','c')
print(Fleet8_Filter.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              format.args = list(big.mark = ","))



Fleet8_AIC.table = xtable(Fleet8_AIC,
                            caption = c("Model selection for the PISCO dive survey data."),
                            label='tab:Fleet8_AIC')

print(Fleet8_AIC.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})


```

\FloatBarrier

<!-- ********************************************************************** -->
<!-- *****Fleet 9 index TABLES******* -->
<!-- ********************************************************************** -->

```{r, results="asis"}
#read in index summary data for CCFRP
Fleet9_Filter = read.xlsx('./txt_files/Fleet9_CCFRP_IndexData.xlsx', 
                            sheetName='Filter', header = T)

Fleet9_AIC = read.xlsx('./txt_files/Fleet9_CCFRP_IndexData.xlsx', sheetName='AIC', header=T)

colnames(Fleet9_Filter) = c('Filter','Drifts','Positive Drifts')

Fleet9_Filter.table = xtable(Fleet9_Filter,
                       caption = c("Data filtering steps for the fishery-independent CCFRP hook-and-line survey."),
                       label = 'tab:Fleet9_Filter',
                       digits = 0)


align(Fleet9_Filter.table) = c('l',
                               '>{\\raggedright}p{3.5in}',
                               'c',
                               '>{\\centering}p{1.4in}')
                   
print(Fleet9_Filter.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              format.args = list(big.mark = ","))



Fleet9_AIC.table = xtable(Fleet9_AIC,
                            caption = c("Model selection for the fishery-independent CCFRP hook-and-line survey."),
                            label='tab:Fleet9_AIC')

print(Fleet9_AIC.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})


```



\FloatBarrier

<!-- ********************************************************************** -->
<!-- *****Fleets 10 and 11 index TABLES******* -->
<!-- ********************************************************************** -->


```{r, results="asis"}
#read in index summary data for 2 MRFSS dockside indices
Fleet10_11_Filter = read.xlsx('./txt_files/Fleet10and11_MRFSSDockside_IndexData.xlsx', 
                            sheetName='BothFilter', header = T)

Fleet10_AIC = read.xlsx('./txt_files/Fleet10and11_MRFSSDockside_IndexData.xlsx', sheetName='NorthAIC', header=T)
Fleet11_AIC = read.xlsx('./txt_files/Fleet10and11_MRFSSDockside_IndexData.xlsx', sheetName='SouthAIC', header=T)


colnames(Fleet10_11_Filter) = c('Filter','Trips','Positive Trips')
Fleet10_11_Filter[4,] = c(NA,NA,NA)
Fleet10_11_Filter[9,] = c(NA,NA,NA)

Fleet10_11_Filter.table = xtable(Fleet10_11_Filter,
                               caption = c("Data filtering steps for the MRFSS dockside intercept survey 
                                           index of abundance for north and south of Pt. Conception."),
                               label = 'tab:Fleet10_11_Filter', digits = 0,
                               format.args = list(big.mark = ",",))

align(Fleet10_11_Filter.table) = c('l','l','c','c')

print(Fleet10_11_Filter.table, 
              include.rownames=FALSE, 
              caption.placement="top")


Fleet10_AIC.table = xtable(Fleet10_AIC,
                            caption = c("Model selection for the MRFSS dockside intercept survey 
                                        north of Pt. Conception. Bold 
                                        values indicate the model selected."),
                            label='tab:Fleet10_AIC')

print(Fleet10_AIC.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})


Fleet11_AIC.table = xtable(Fleet11_AIC,
                            caption = c("Model selection for the MRFSS dockside intercept 
                                        survey south of Pt. Conception. Bold 
                                        values indicate the model selected."),
                            label='tab:Fleet11_AIC')

print(Fleet11_AIC.table, 
              include.rownames=FALSE, 
              caption.placement="top",
              sanitize.text.function = function(x){x})
     
```

```{r, results="asis"}
#Make the contingency table for GBYR MRFSS north

b = c("Above 0.4",186,437)
c = c("Below 0.4",1982,183)

Fleet10_cont = rbind(b,c)
colnames(Fleet10_cont) = c(" ","GBYR absent","GBYR present")

Fleet10_cont.table = xtable(Fleet10_cont,
                               caption = c("Contingency table for the Stephens-MacCall 
                                            filtering for the MRFSS dockside CPFV index 
                                            for GBYR north of Pt. Conception."),big.mark=",",
                               label = 'tab:Fleet10_contingency')

align(Fleet10_cont.table) = c('l','r','c','c')

print(Fleet10_cont.table, 
              include.rownames=FALSE, 
              caption.placement="top")
```

```{r, results="asis"}
#Make the contingency table for GBYR MRFSS north

b = c("Above 0.22",246,184)
c = c("Below 0.22",6647,257)

Fleet11_cont = rbind(b,c)
colnames(Fleet11_cont) = c(" ","GBYR absent","GBYR present")

Fleet11_cont.table = xtable(Fleet11_cont,
                               caption = c("Contingency table for the Stephens-MacCall 
                                            filtering for the MRFSS dockside CPFV index 
                                            for GBYR south of Pt. Conception."),big.mark=",",
                               label = 'tab:Fleet11_contingency')

align(Fleet11_cont.table) = c('l','r','c','c')

print(Fleet11_cont.table, 
              include.rownames=FALSE, 
              caption.placement="top")
```

\FloatBarrier

<!-- ********************************************************************** -->
<!-- *****Table of available ages******* -->
<!-- ********************************************************************** -->

```{r, results="asis"}

Age_data = read.csv('./txt_files/Age_data.csv')

Age_data.table = xtable(Age_data,
                        caption = c('Summary of age data used in the assessment.'),
                        label = 'tab:Age_data')


align(Age_data.table) = c('l',
                         '>{\\raggedright}p{1.6in}',
                          'l',
                          '>{\\raggedright}p{1.3in}',
                         '>{\\raggedright}p{1.3in}',
                         '>{\\raggedright}p{1in}',
                         '>{\\raggedright}p{1in}',
                         '>{\\raggedright}p{1in}')

print(Age_data.table,
      include.rownames = FALSE,
      caption.placement="top",
       floating.environment = 'sidewaystable',
      sanitize.text.function = function(x){x})




```