---
title: ''
author: ''
date: ''
output:
  pdf_document:
    fig_caption: yes
    highlight: haddock
    includes:
      in_header: header.tex
    keep_tex: yes
    latex_engine: xelatex
    template: Default_template_modified.tex
    number_sections: yes
    toc: yes
    toc_depth: 4
  html_document:
    toc: yes
  word_document: default
documentclass: article
fontsize: 12pt
geometry: margin=1in
csl: CJFAS.csl
bibliography: BibFile.bib
---
```{r global_options, include=FALSE}
    # set global options for R code chunks: echo=FALSE (don't include source code); 
    # warning=FALSE (suppress R warnings); message=FALSE (suppress R messages)
    # eval = TRUE is default
    knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
    # Read in preamble R code - including required libraries and the SS file(s)
    source('./Rcode/Preamble.R')
    source("./Rcode/MultiHeader.R")
    # Read in data/manipulations for executive summary tables and figures
    # It may take time to edit this file and get it ready for your assessment
    # Make small changes in this file and then try to compile the document
    # Commit when you have a success!
    source('./Rcode/Exec_summary_figs_tables.R')
```

USE THIS .Rmd TO TEST R CODE CHUNKS, FIGURES AND PLOTS BEFORE INSERTING INTO THE MAIN TEXT OR TO DEBUG


```{r, results = 'asis'}
#Read in lengths table, make one for n fish lengthed and one for trips
#Fishery dependent data
lengths_sample = read.csv('C:/GopherBlackYellow2019/txt_files/LengthSampleSize2.csv')
lengths_sample = lengths_sample[,1:11]
#Make the multiheader table
colnames(lengths_sample) = c('Year','Trips','Lengths','Trips','Lengths','Trips','Lengths',
                                 'Trips','Lengths','Trips','Lengths')

a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  lengths_sample,
  # the labels of the groups that we want to insert
  grp_names = c("", "CALCOM", "WCGOP","Rec North","Rec South",
                     "Deb VW"),
  # the number of columns each group spans
  span = c(1, 2, 2, 2, 2, 2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)

caption = "Length composition sample sizes for fishery dependent data. Continuous years begin in 1975. 
           Recreational north samples include Karpov et al., MRFSS, and CRFS data. 
           Recreational south samples include Karpov et al., Collins and Crooke unpub.,
           Ally et al. 1975, MRFSS, and CRFS data."

lengths.table = xtable(lengths_sample,
                    caption = caption,
                    label = 'tab:length_samples_fishery')

align(lengths.table) = c('l', 'l',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}')

print(lengths.table, add.to.row = a_header, 
      caption.placement = "top", 
      include.rownames = F, hline.after = F, scalebox = .76)
```

```{r, results = 'asis'}
#Read in lengths table, make one for n fish lengthed and one for trips
#Fishery independent data
lengths_sample1 = read.csv('C:/GopherBlackYellow2019/txt_files/LengthSampleSize2.csv')
lengths_sample1 = lengths_sample1 %>%
                  select(Year, CCFRPT:PISCOF) %>%
                  filter(Year>2000)
#Make the multiheader table
colnames(lengths_sample1) = c('Year','Trips','Lengths','Trips','Lengths')

a_header <- construct_header(
  # the data.frame or matrix that should be plotted
  lengths_sample1,
  # the labels of the groups that we want to insert
  grp_names = c("","CCFRP","PISCO"),
  # the number of columns each group spans
  span = c(1, 2, 2),
  # the alignment of each group, can be a single character (lcr) or a vector
  align = "c"
)

caption = "Length composition sample sizes for survey data."

lengths.table = xtable(lengths_sample1,
                    caption = caption,
                    label = 'tab:length_samples_survey')

align(lengths.table) = c('l', 'l',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}',
                               '>{\\centering}p{0.6in}')

print(lengths.table, add.to.row = a_header, 
      caption.placement = "top", 
      include.rownames = F, hline.after = F)
```

